apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["t3.micro"]
    desiredCapacity: 1



# eksctl create cluster --config-file=eks_creation.yaml